language: node_js
node_js:
  - node
cache:
  directories:
    - ~/.npm
    - .jest
jobs:
  include:
    - stage: test
      script:
        - yarn test:ci
    - stage: deploy
      before_deploy:
        - yarn semantic-release
      deploy:
        provider: heroku
        app: express-ts-starter
        api_key:
          secure: $HEROKU_KEY
