language: node_js
node_js:
  - node
cache:
  directories:
    - ~/.npm
    - .jest
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  on:
    repo: express-ts-starter
jobs:
  include:
    - stage: test
      script:
        - yarn test:ci
    - stage: 'Version bump'
      script:
        - yarn semantic-release
