branches:
  only:
    - master
  # Don't run CI on tag push
  except:
    - /^v\d+\.\d+\.\d+$/
language: node_js
node_js:
  - node
cache:
  directories:
    - '~/.npm'
    - '.jest'
jobs:
  include:
    - stage: test
      script:
        - yarn test:ci
    - stage: deploy
      before_deploy:
        - yarn semantic-release
      deploy:
        provider: heroku
        app: express-ts-starter
        # Exposing the API key seems to be the only way to get travis to call heroku build API properly
        # And this is a public key which is only decryptable by Travis so technically it is safe to expose it
        # Source: https://docs.travis-ci.com/user/encryption-keys/
        api_key:
          secure: $HEROKU_API_KEY
