language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: express-ts-starter
  on:
    repo: thousight/express-ts-starter
jobs:
  include:
    - stage: test
      script:
        - yarn test --ci
    - stage: 'Version bump'
      script:
        - yarn semantic-release
